const products=[
 {id:'ring',name:'Ring',prices:{Standard:75}},
 {id:'octopus',name:'Octopus',prices:{White:100,Green:100,Red:110,Multicolor:125}},
 {id:'kirby',name:'Kirby',prices:{White:20,Green:20,Red:25}},
 {id:'half-octopus',name:'Half-size Octopus',prices:{White:65,Green:65,Red:75,Multicolor:85}},
 {id:'infinity-cube',name:'Infinity Cube',prices:{White:75,Green:75}},
 {id:'weighted-cube',name:'Weighted Infinity Cube',prices:{White:125,Green:125}}
];
const cart=[];const money=c=>`$${(c/100).toFixed(2)}`;
function productCard(p){const opts=Object.entries(p.prices).map(([c,v])=>`<option value="${c}" data-price="${v}">${c} — ${money(v)}</option>`).join('');return `<article class="product"><h3>${p.name}</h3><div class="price" id="price-${p.id}">${money(Object.values(p.prices)[0])}</div><label>Color<select id="color-${p.id}" onchange="updatePrice('${p.id}')">${opts}</select></label><button class="add" onclick="addItem('${p.id}')">Add to cart</button></article>`}
document.querySelector('#products').innerHTML=products.map(productCard).join('');
window.updatePrice=id=>{const s=document.querySelector(`#color-${id}`);document.querySelector(`#price-${id}`).textContent=money(Number(s.selectedOptions[0].dataset.price))};
window.addItem=id=>{const p=products.find(x=>x.id===id),color=document.querySelector(`#color-${id}`).value,price=p.prices[color],found=cart.find(x=>x.productId===id&&x.color===color);if(found)found.quantity++;else cart.push({productId:id,name:p.name,color,unitPrice:price,quantity:1});renderCart()};
window.changeQty=(i,d)=>{cart[i].quantity+=d;if(cart[i].quantity<1)cart.splice(i,1);renderCart()};window.removeItem=i=>{cart.splice(i,1);renderCart()};
function renderCart(){const count=cart.reduce((s,x)=>s+x.quantity,0),total=cart.reduce((s,x)=>s+x.quantity*x.unitPrice,0);document.querySelector('#cartCount').textContent=count;document.querySelector('#total').textContent=money(total);document.querySelector('#cartItems').innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row"><div><strong>${x.name}</strong><small>${x.color} · ${money(x.unitPrice)} each</small></div><div class="qty"><button aria-label="Decrease" onclick="changeQty(${i},-1)">−</button><b>${x.quantity}</b><button aria-label="Increase" onclick="changeQty(${i},1)">+</button></div><button class="remove" onclick="removeItem(${i})">Remove</button></div>`).join(''):'<div class="empty">Your cart is empty.</div>'}
document.querySelector('#orderForm').addEventListener('submit',async e=>{e.preventDefault();const msg=document.querySelector('#message'),btn=document.querySelector('#submitBtn');msg.className='message full';msg.textContent='';if(!cart.length){msg.classList.add('error');msg.textContent='Add at least one item to your cart.';return}btn.disabled=true;btn.textContent='Submitting…';const f=new FormData(e.target),body={firstName:f.get('firstName'),classColor:f.get('classColor'),email:f.get('email'),paymentMethod:f.get('paymentMethod'),notes:f.get('notes'),items:cart.map(({productId,color,quantity})=>({productId,color,quantity}))};try{const res=await fetch('/api/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),data=await res.json();if(!res.ok)throw new Error(data.error||'Could not place order.');msg.classList.add('success');msg.innerHTML=`Order placed! Your order number is <strong>${data.orderId}</strong>. Total: <strong>${money(data.totalCents)}</strong>.`;cart.splice(0);renderCart();e.target.reset()}catch(err){msg.classList.add('error');msg.textContent=err.message}finally{btn.disabled=false;btn.textContent='Place order'}});
renderCart();
